### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by RtzX** [LiuC520/react-native-city-pick#1]
参考了城市选择列表.项目需要加入了搜索功能.用了 for each in ..去匹配..但是有点延迟.体验不是很好. 有什么更好的解决办法吗?? 谢谢

**Comment by LiuC520** [comment]
https://github.com/rgovindji/react-native-atoz-list
你好，你看下这个，这个写的要多一些，我那个数据多了会卡的，这个应该好点儿
