### ISSUE TITLE
在列表模式下，右边的letter可以变成滑动的么

### ISSUE THREAD

**Issue by buptyyf** [LiuC520/react-native-city-pick#2]
如题，右边的letter能不能改成和微信通讯录那样一样的，可以滑动着变化左边的名单，而不是通过只能点击呢，rn中有提供这种方法么？

**Comment by LiuC520** [comment]
可以的，你在list.js文件中，修改下render里面的
`<View style={styles.letters}>
         {letters.map((letter, index) => this.renderLetters(letter, index))}
   </View>`
这个方法就可以了，把view换成scrollview

**Comment by buptyyf** [comment]
我试了一下，改成
```javascript
<ScrollView style={styles.letters} > {letters.map((letter, index) => this.renderLetters(letter, index))} </ScrollView>
```
然后把styles.letters中的justifyContent和alignItems删掉才能不报错，但是还是不行，效果和View的一样，并不能实现手指不离开索引字母进行滑动，左边动态变化的效果啊，是不是改的不对？
